// ─────────────────────────────────────────────────────────────────────────────
// JERA ON AIR 2026 — TIMETABLE DATA
// Pas dit bestand aan om artiesten, tijden, podia of festivalnaam te wijzigen.
// ─────────────────────────────────────────────────────────────────────────────

const FESTIVAL = {
  name:    'Jera On Air',
  edition: '2026',
  url:     'https://www.jeraonair.nl/nl/',
  lineup_base_url: 'https://www.jeraonair.nl/nl/line-up/',
  storage_key: 'jera_liked26',    // localStorage key for liked acts
  day_key:     'jera_day',        // localStorage key for active day
};

// ─── DAYS ────────────────────────────────────────────────────────────────────
// id:    used internally and in localStorage keys
// label: full Dutch name shown in the side panel
// short: abbreviation shown in the header tabs
// date:  shown below the abbreviation
const DAYS = [
  { id: 'THU', label: 'Donderdag', short: 'DO', date: '25 jun' },
  { id: 'FRI', label: 'Vrijdag',   short: 'VR', date: '26 jun' },
  { id: 'SAT', label: 'Zaterdag',  short: 'ZA', date: '27 jun' },
];

// ─── STAGES ──────────────────────────────────────────────────────────────────
// id:    must match the keys used in SCHEDULE below
// name:  displayed in the stage header column
// color: block background color (hex)
const STAGES = [
  { id: 'eagle',    name: 'Eagle',    color: '#7c3aed' },
  { id: 'vulture',  name: 'Vulture',  color: '#0ea5e9' },
  { id: 'buzzard',  name: 'Buzzard',  color: '#10b981' },
  { id: 'hawk',     name: 'Hawk',     color: '#f59e0b' },
  { id: 'sparrow',  name: 'Sparrow',  color: '#ef4444' },
  { id: 'raven',    name: 'Raven',    color: '#ec4899' },
  { id: 'quail',    name: 'Quail',    color: '#14b8a6' },
];

// ─── ARTIST SLUG MAP ─────────────────────────────────────────────────────────
// Maps artist display name → URL slug for the lineup page.
// If an artist has no slug they won't get a link (clicking name does nothing).
const SLUGS = {
  'Architects':                 'architects',
  'Boundaries':                 'boundaries',
  'Decapitated':                'decapitated',
  'Set It Off':                 'set-it-off',
  'Alexisonfire':               'alexisonfire',
  'Trivium':                    'trivium',
  'Dying Wish':                 'dying-wish',
  'Wargasm':                    'wargasm',
  'Bury Tomorrow':              'bury-tomorrow',
  'Pennywise':                  'pennywise',
  'Rise Against':               'rise-against',
  'Ways Away':                  'ways-away',
  'Whispers':                   'whispers',
  'Fiddlehead':                 'fiddlehead',
  'Madball':                    'madball',
  'Converge':                   'converge',
  'Basement':                   'basement',
  'Speedway':                   'speedway',
  'Nevertel':                   'nevertel',
  'Quicksand':                  'quicksand',
  'The Ataris':                 'the-ataris',
  'The Menzingers':             'the-menzingers',
  'Rotzak':                     'rotzak',
  'Domain':                     'domain',
  'Feels Like Heaven':          'feels-like-heaven',
  'The Smith Street Band':      'the-smith-street-band',
  'TSS':                        'tss',
  'Aurorawave':                 'aurorawave',
  'De Rooie Jager':             'de-rooie-jager',
  'NØFX':                       'neufx',
  'Dynamo Heavy Bingo':         'dynamo-heavy-bingo',
  'Emo Night Mainland':         'emo-night-mainland',
  'The Offspring':              'the-offspring',
  'ALLT':                       'allt',
  'TX2':                        'tx2',
  'Annisokay':                  'annisokay',
  'Alkaline Trio':              'alkaline-trio',
  'Hollywood Undead':           'hollywood-undead',
  'A Day To Remember':          'a-day-to-remember',
  'Heriot':                     'heriot',
  'Melrose Avenue':             'melrose-avenue',
  'Ho99o9':                     'ho99o9',
  'Thrown':                     'thrown',
  'Periphery':                  'periphery',
  'Suicidal Tendencies':        'suicidal-tendencies',
  'Ice Nine Kills':             'ice-nine-kills',
  'Curselifter':                'curselifter',
  'Gridiron':                   'gridiron',
  'Haywire':                    'haywire',
  'King 810':                   'king-810',
  'Ignite':                     'ignite',
  'Destroy Boys':               'destroy-boys',
  'Malevolence':                'malevolence',
  'Trash Talk':                 'trash-talk',
  'Belvedere':                  'belvedere',
  'Magnolia Park':              'magnolia-park',
  'The Flatliners':             'the-flatliners',
  'The Baboon Show':            'the-baboon-show',
  'Jaya The Cat':               'jaya-the-cat',
  'Bad Nerves':                 'bad-nerves',
  'Paceshifters Play Nirvana':  'paceshifters-play-nirvana',
  'Ilænder':                    'ilaender',
  'The Dwarves':                'dwarves',
  'Politie Warnsveld':          'politie-warnsveld',
  'Upchuck':                    'upchuck',
  'Kings of Schrobbeler':       'kings-of-schrobbeler',
  'Captain Kaiser':             'captain-kaiser',
  'Geishas of Doom ft Rudeboy': 'geishas-of-doom',
  'Grade 2':                    'grade-2',
  'Authority Zero':             'authority-zero',
  'Elle Rich':                  'elle-rich',
  'The Viper':                  'the-viper',
  'Real Paradise Group':        'real-paradise-group',
  "Q'N":                        'qn',
  'Andy & The Antichrist':      'andy-and-the-antichrist',
  'Leblanc':                    'leblanc',
  'Fresku':                     'fresku',
  'Deathbyromy':                'deathbyromy',
  'Code: Pandorum Live':        'code-pandorum',
  'TDC Inc':                    'tdc-inc',
  'Parrish Smith Live':         'parrish-smith',
  'Papa Roach':                 'papa-roach',
  'Rain City Drive':            'rain-city-drive',
  'Catch Your Breath':          'catch-your-breath',
  'La Dispute':                 'la-dispute',
  'Imminence':                  'imminence',
  'All Time Low':               'all-time-low',
  'Viagra Boys':                'viagra-boys',
  'Mouth Culture':              'mouth-culture',
  'Our Mirage':                 'our-mirage',
  'Ten56.':                     'ten56',
  'Distant':                    'distant',
  'Kanonenfieber':              'kanonenfieber',
  'Turbonegro':                 'turbonegro',
  'Hatebreed':                  'hatebreed',
  'Even If We Lose':            'even-if-we-lose',
  'Combust':                    'combust',
  'Desolated':                  'desolated',
  'Doodseskader':               'doodseskader',
  'End It':                     'end-it',
  'We Came As Romans':          'we-came-as-romans',
  'Bob Vylan':                  'bob-vylan',
  'Get The Shot':               'get-the-shot-',
  'Sugar Spine':                'sugar-spine',
  'Have Mercy':                 'have-mercy',
  'Trash Boat':                 'trash-boat',
  'Free Throw':                 'free-throw',
  'Talco':                      'talco',
  'Dog Eat Dog':                'dog-eat-dog',
  'Alle Kleuren':               'alle-kleuren',
  'Torn From Oblivion':         'torn-from-oblivion',
  'Wuf':                        'wijf',
  'Initiate':                   'initiate',
  'Taxitaxi':                   'taxitaxi',
  'The JB Conspiracy':          'the-jb-conspiracy',
  'Ronker':                     'ronker',
  'Gabbertje':                  'gabbertje',
  'Unpeople':                   'unpeople',
  'Zeke':                       'zeke',
  'Het Goede Doel':             'het-goede-doel',
  'The Aggrolites':             'the-aggrolites',
  'Alienia':                    'aliienmia',
  'Panic':                      'panic',
  'Clitteband':                 'clitteband',
  'Lola Doppelspitze':          'lola-doppelspitze',
  'Zalm':                       'zalm',
  'Youth Code':                 'youth-code',
  'Ray Fuego':                  'ray-fuego',
  'Jawat!':                     'jawat',
  'Kleine Crack & Slagter':     'kleine-crack-and-slagter',
  'Gierboys':                   'gierboys',
  'Kaboutertje Putlucht':       'kaboutertje-putlucht',
};

// ─── SCHEDULE ────────────────────────────────────────────────────────────────
// Structure: SCHEDULE[day_id][stage_id] = array of acts
// Each act: { a: 'Artist Name', s: 'HH:MM', e: 'HH:MM' }
//   a = artist name (must match a key in SLUGS if you want a lineup link)
//   s = start time  (times after midnight use 00:xx, 01:xx etc.)
//   e = end time
const SCHEDULE = {

  // ── DONDERDAG 25 JUN ──────────────────────────────────────────────────────
  THU: {
    eagle: [
      { a: 'Boundaries',        s: '15:00', e: '15:30' },
      { a: 'Decapitated',       s: '16:00', e: '16:50' },
      { a: 'Set It Off',        s: '18:00', e: '18:50' },
      { a: 'Alexisonfire',      s: '20:00', e: '20:50' },
      { a: 'Trivium',           s: '22:00', e: '22:50' },
      { a: 'Architects',        s: '00:00', e: '01:00' },
    ],
    vulture: [
      { a: 'Dying Wish',        s: '15:30', e: '16:00' },
      { a: 'Wargasm',           s: '17:00', e: '17:50' },
      { a: 'Bury Tomorrow',     s: '19:00', e: '19:50' },
      { a: 'Pennywise',         s: '21:00', e: '21:50' },
      { a: 'Rise Against',      s: '23:00', e: '23:50' },
    ],
    buzzard: [
      { a: 'Ways Away',         s: '15:30', e: '16:00' },
      { a: 'Whispers',          s: '17:00', e: '17:45' },
      { a: 'Fiddlehead',        s: '19:00', e: '19:50' },
      { a: 'Madball',           s: '21:00', e: '21:50' },
      { a: 'Converge',          s: '23:00', e: '23:50' },
    ],
    hawk: [
      { a: 'Speedway',          s: '15:00', e: '15:30' },
      { a: 'Nevertel',          s: '16:00', e: '16:50' },
      { a: 'Quicksand',         s: '18:00', e: '18:50' },
      { a: 'The Ataris',        s: '20:00', e: '20:50' },
      { a: 'The Menzingers',    s: '22:00', e: '22:50' },
      { a: 'Basement',          s: '00:00', e: '01:00' },
    ],
    sparrow: [
      { a: 'Rotzak',            s: '15:00', e: '15:30' },
      { a: 'Domain',            s: '16:30', e: '17:00' },
      { a: 'Feels Like Heaven', s: '17:45', e: '18:15' },
      { a: 'The Smith Street Band', s: '18:45', e: '19:30' },
      { a: 'TSS',               s: '20:15', e: '21:00' },
      { a: 'Aurorawave',        s: '21:45', e: '22:30' },
      { a: 'De Rooie Jager',    s: '22:45', e: '23:50' },
      { a: 'NØFX',             s: '23:50', e: '01:00' },
    ],
    raven: [
      { a: 'Dynamo Heavy Bingo', s: '15:00', e: '18:00' },
      { a: 'Emo Night Mainland', s: '18:00', e: '01:00' },
    ],
    quail: [],
  },

  // ── VRIJDAG 26 JUN ───────────────────────────────────────────────────────
  FRI: {
    eagle: [
      { a: 'ALLT',              s: '12:45', e: '13:25' },
      { a: 'TX2',               s: '14:15', e: '14:55' },
      { a: 'Annisokay',         s: '16:00', e: '16:50' },
      { a: 'Alkaline Trio',     s: '18:00', e: '18:50' },
      { a: 'Hollywood Undead',  s: '20:00', e: '20:50' },
      { a: 'A Day To Remember', s: '22:00', e: '22:50' },
      { a: 'The Offspring',     s: '00:00', e: '01:00' },
    ],
    vulture: [
      { a: 'Heriot',            s: '12:00', e: '12:40' },
      { a: 'Melrose Avenue',    s: '13:30', e: '14:10' },
      { a: 'Ho99o9',            s: '15:00', e: '15:50' },
      { a: 'Thrown',            s: '17:00', e: '17:50' },
      { a: 'Periphery',         s: '19:00', e: '19:50' },
      { a: 'Suicidal Tendencies', s: '21:00', e: '21:50' },
      { a: 'Ice Nine Kills',    s: '23:00', e: '23:50' },
    ],
    buzzard: [
      { a: 'Curselifter',       s: '12:00', e: '12:40' },
      { a: 'Gridiron',          s: '13:30', e: '14:10' },
      { a: 'Haywire',           s: '15:00', e: '15:50' },
      { a: 'King 810',          s: '17:00', e: '17:50' },
      { a: 'Ignite',            s: '19:00', e: '19:50' },
      { a: 'Destroy Boys',      s: '21:00', e: '21:50' },
      { a: 'Malevolence',       s: '23:00', e: '23:50' },
    ],
    hawk: [
      { a: 'Belvedere',         s: '12:45', e: '13:25' },
      { a: 'Magnolia Park',     s: '14:15', e: '14:55' },
      { a: 'The Flatliners',    s: '16:00', e: '16:50' },
      { a: 'The Baboon Show',   s: '18:00', e: '18:50' },
      { a: 'Jaya The Cat',      s: '20:00', e: '20:50' },
      { a: 'Bad Nerves',        s: '22:00', e: '22:50' },
      { a: 'Trash Talk',        s: '00:00', e: '01:00' },
    ],
    sparrow: [
      { a: 'Ilænder',           s: '12:30', e: '13:00' },
      { a: 'The Dwarves',       s: '13:30', e: '14:00' },
      { a: 'Politie Warnsveld', s: '14:30', e: '15:00' },
      { a: 'Upchuck',           s: '15:30', e: '16:15' },
      { a: 'Kings of Schrobbeler', s: '16:45', e: '17:30' },
      { a: 'Captain Kaiser',    s: '18:15', e: '19:00' },
      { a: 'Geishas of Doom ft Rudeboy', s: '19:45', e: '20:30' },
      { a: 'Grade 2',           s: '21:15', e: '22:00' },
      { a: 'Authority Zero',    s: '22:45', e: '23:30' },
      { a: 'Paceshifters Play Nirvana', s: '00:15', e: '01:00' },
      { a: 'De Rooie Jager',    s: '01:00', e: '02:00' },
    ],
    raven: [
      { a: 'Real Paradise Group', s: '14:00', e: '14:45' },
      { a: "Q'N",               s: '14:45', e: '15:30' },
      { a: 'Andy & The Antichrist', s: '16:00', e: '16:30' },
      { a: 'Leblanc',           s: '17:00', e: '17:30' },
      { a: 'Fresku',            s: '18:00', e: '18:30' },
      { a: 'Deathbyromy',       s: '19:00', e: '19:30' },
      { a: 'Code: Pandorum Live', s: '20:00', e: '21:00' },
      { a: 'TDC Inc',           s: '21:30', e: '22:30' },
      { a: 'Parrish Smith Live', s: '23:00', e: '00:00' },
      { a: 'Elle Rich',         s: '00:00', e: '01:00' },
      { a: 'The Viper',         s: '01:00', e: '02:00' },
    ],
    quail: [],
  },

  // ── ZATERDAG 27 JUN ──────────────────────────────────────────────────────
  SAT: {
    eagle: [
      { a: 'Rain City Drive',   s: '12:45', e: '13:25' },
      { a: 'Catch Your Breath', s: '14:15', e: '14:55' },
      { a: 'La Dispute',        s: '16:00', e: '16:50' },
      { a: 'Imminence',         s: '18:00', e: '18:50' },
      { a: 'All Time Low',      s: '20:00', e: '20:50' },
      { a: 'Viagra Boys',       s: '22:00', e: '22:50' },
      { a: 'Papa Roach',        s: '00:00', e: '01:00' },
    ],
    vulture: [
      { a: 'Mouth Culture',     s: '12:00', e: '12:40' },
      { a: 'Our Mirage',        s: '13:30', e: '14:10' },
      { a: 'Ten56.',            s: '15:00', e: '15:50' },
      { a: 'Distant',           s: '17:00', e: '17:50' },
      { a: 'Kanonenfieber',     s: '19:00', e: '19:50' },
      { a: 'Turbonegro',        s: '21:00', e: '21:50' },
      { a: 'Hatebreed',         s: '23:00', e: '23:50' },
    ],
    buzzard: [
      { a: 'Even If We Lose',   s: '12:00', e: '12:40' },
      { a: 'Combust',           s: '13:30', e: '14:10' },
      { a: 'Desolated',         s: '15:00', e: '15:50' },
      { a: 'Doodseskader',      s: '17:00', e: '17:50' },
      { a: 'End It',            s: '19:00', e: '19:50' },
      { a: 'We Came As Romans', s: '21:00', e: '21:50' },
      { a: 'Bob Vylan',         s: '23:00', e: '23:50' },
    ],
    hawk: [
      { a: 'Sugar Spine',       s: '12:45', e: '13:25' },
      { a: 'Have Mercy',        s: '14:15', e: '14:55' },
      { a: 'Trash Boat',        s: '16:00', e: '16:50' },
      { a: 'Free Throw',        s: '18:00', e: '18:50' },
      { a: 'Talco',             s: '20:00', e: '20:50' },
      { a: 'Dog Eat Dog',       s: '22:00', e: '22:50' },
      { a: 'Get The Shot',      s: '00:00', e: '01:00' },
    ],
    sparrow: [
      { a: 'Torn From Oblivion', s: '12:00', e: '12:30' },
      { a: 'Wuf',               s: '13:00', e: '13:30' },
      { a: 'Initiate',          s: '14:00', e: '14:30' },
      { a: 'Taxitaxi',          s: '15:00', e: '15:30' },
      { a: 'The JB Conspiracy', s: '16:00', e: '16:45' },
      { a: 'Ronker',            s: '17:15', e: '18:00' },
      { a: 'Gabbertje',         s: '18:15', e: '18:45' },
      { a: 'Unpeople',          s: '19:00', e: '19:45' },
      { a: 'Zeke',              s: '20:15', e: '21:00' },
      { a: 'Het Goede Doel',    s: '21:30', e: '22:15' },
      { a: 'The Aggrolites',    s: '23:00', e: '23:45' },
      { a: 'Alle Kleuren',      s: '00:15', e: '01:00' },
      { a: 'De Rooie Jager',    s: '01:00', e: '02:00' },
    ],
    raven: [
      { a: 'Real Paradise Group', s: '14:00', e: '14:45' },
      { a: 'Clitteband',        s: '14:45', e: '15:30' },
      { a: 'Lola Doppelspitze', s: '16:00', e: '16:30' },
      { a: 'Zalm',              s: '17:00', e: '17:30' },
      { a: 'Youth Code',        s: '18:00', e: '18:45' },
      { a: 'Ray Fuego',         s: '19:00', e: '19:45' },
      { a: 'Jawat!',            s: '20:00', e: '20:45' },
      { a: 'Kleine Crack & Slagter', s: '21:30', e: '22:00' },
      { a: 'Gierboys',          s: '22:15', e: '22:45' },
      { a: 'Kaboutertje Putlucht', s: '23:15', e: '00:00' },
      { a: 'Alienia',           s: '00:00', e: '01:00' },
      { a: 'Panic',             s: '01:00', e: '02:00' },
    ],
    quail: [],
  },

};
